---
controller_credentials_all:
  - name: AWX_LINUX_CRED
    credential_type: Machine
    organization: AWXPOC
    description: Linux SSH credential (from vault.yml)
    inputs:
      username: "{{ linux_user }}"
      password: "{{ linux_password }}"
  - name: AWX_WINDOWS_CRED
    credential_type: Machine
    organization: AWXPOC
    description: Windows WinRM credential (from vault.yml)
    inputs:
      username: "{{ windows_user }}"
      password: "{{ windows_password }}"


# =====================================================
  - name: CRE_LDC_AAP_SPN_Credential%dev%
    credential_type: CRT_LDC_AAP_SPN_Credential
    organization: AWXPOC
    description: LDC AAP SPN
    inputs:
      azure_tenant_id: "{{ ldc_aap_spn_tenant_id }}"
      azure_client_id: "{{ ldc_aap_spn_client_id }}"
      azure_client_secret: "{{ ldc_aap_spn_client_secret }}"

  - name: CRE_LDC_AAP_SPN_Credential%prd%
    credential_type: CRT_LDC_AAP_SPN_Credential
    organization: AWXPOC
    description: LDC AAP SPN
    inputs:
      azure_tenant_id: "{{ ldc_aap_spn_tenant_id }}"
      azure_client_id: "{{ ldc_aap_spn_client_id }}"
      azure_client_secret: "{{ ldc_aap_spn_client_secret }}"
# =====================================================
  - name: CRE_LDC_AAP_SPN_TEST_Credential%dev%
    credential_type: CRT_LDC_AAP_SPN_TEST_Credential
    organization: AWXPOC
    description: LDC AAP SPN TEST DEV
    inputs:
      test_tenant_id: "{{ ldc_aap_spn_test_tenant_id }}"
      test_client_id: "{{ ldc_aap_spn_test_client_id }}"
      test_client_secret: "{{ ldc_aap_spn_test_client_secret }}"

  - name: CRE_LDC_AAP_SPN_TEST_Credential%prd%
    credential_type: CRT_LDC_AAP_SPN_TEST_Credential
    organization: AWXPOC
    description: LDC AAP SPN TEST PRD
    inputs:
      test_tenant_id: "{{ ldc_aap_spn_test_tenant_id }}"
      test_client_id: "{{ ldc_aap_spn_test_client_id }}"
      test_client_secret: "{{ ldc_aap_spn_test_client_secret }}"

# =====================================================
  - name: CRE_LDC_AAP_SPN_China_Credential_TEST%dev%
    credential_type: CRT_LDC_AAP_SPN_China_Test_Credential
    organization: AWXPOC
    description: LDC AAP SPN CHINA TEST
    inputs:
      china_test_tenant_id: "{{ ldc_aap_spn_china_test_tenant_id }}"
      china_test_client_id: "{{ ldc_aap_spn_china_test_client_id }}"
      china_test_client_secret: "{{ ldc_aap_spn_china_test_secret }}"

  - name: CRE_LDC_AAP_SPN_China_Credential_TEST%prd%
    credential_type: CRT_LDC_AAP_SPN_China_Test_Credential
    organization: AWXPOC
    description: LDC AAP SPN CHINA TEST PROD
    inputs:
      china_test_tenant_id: "{{ ldc_aap_spn_china_test_tenant_id }}"
      china_test_client_id: "{{ ldc_aap_spn_china_test_client_id }}"
      china_test_client_secret: "{{ ldc_aap_spn_china_test_secret }}"
# =====================================================
  - name: CRE_LDC_AAP_SPN_China_Credential%dev%
    credential_type: CRT_LDC_AAP_SPN_China_Prod_Credential
    organization: AWXPOC
    description: LDC AAP SPN CHINA PROD DEV
    inputs:
      china_prod_tenant_id: "{{ ldc_aap_spn_china_prod_tenant_id }}"
      china_prod_client_id: "{{ ldc_aap_spn_china_prod_client_id }}"
      china_prod_client_secret: "{{ ldc_aap_spn_china_prod_secret }}"

  - name: CRE_LDC_AAP_SPN_China_Credential%prd%
    credential_type: CRT_LDC_AAP_SPN_China_Prod_Credential
    organization: AWXPOC
    description: LDC AAP SPN CHINA PROD
    inputs:
      china_prod_tenant_id: "{{ ldc_aap_spn_china_prod_tenant_id }}"
      china_prod_client_id: "{{ ldc_aap_spn_china_prod_client_id }}"
      china_prod_client_secret: "{{ ldc_aap_spn_china_prod_secret }}"
# =====================================================
