---
controller_credential_types_all:
  - name: AWX Demo Custom Credential
    description: Custom credential type for AWX CAAC demo
    kind: cloud
    inputs:
      fields:
        - id: api_key
          type: string
          label: API Key
          secret: true
      required:
        - api_key
    injectors:
      env:
        DEMO_API_KEY: !unsafe "{{ api_key }}"
      extra_vars:
        demo_api_key: !unsafe "{{ api_key }}"

# =====================================================
# ================== CLOUD START ======================
# =====================================================
  - name: CRT_LDC_AAP_SPN_Credential
    description: LDC AAP SPN credential
    kind: cloud
    inputs:
      fields:
        - id: azure_client_id
          type: string
          label: Client ID
          secret: true
        - id: azure_client_secret
          type: string
          label: Client secret
          secret: true
        - id: azure_tenant_id
          type: string
          label: Tenant ID
          secret: true
      required:
        - azure_client_id
        - azure_client_secret
        - azure_tenant_id

    injectors:
      extra_vars:
        azure_client_id: !unsafe '{{ azure_client_id }}'
        azure_client_secret: !unsafe '{{ azure_client_secret }}'
        azure_tenant_id: !unsafe '{{ azure_tenant_id }}'
# =====================================================
  - name: CRT_LDC_AAP_SPN_TEST_Credential
    description: LDC AAP SPN TEST
    kind: cloud
    inputs:
      fields:
        - id: test_client_id
          type: string
          label: Client ID
          secret: true
        - id: test_client_secret
          type: string
          label: Client secret
          secret: true
        - id: test_tenant_id
          type: string
          label: Tenant ID
          secret: true
      required:
        - test_client_id
        - test_client_secret
        - test_tenant_id

    injectors:
      extra_vars:
        test_client_id: !unsafe '{{ test_client_id }}'
        test_client_secret: !unsafe '{{ test_client_secret }}'
        test_tenant_id: !unsafe '{{ test_tenant_id }}'
# =====================================================
  - name: CRT_LDC_AAP_SPN_China_Test_Credential
    description: LDC AAP SPN China Test credential
    kind: cloud
    inputs:
      fields:
        - id: china_test_client_id
          type: string
          label: Client ID
          secret: true
        - id: china_test_client_secret
          type: string
          label: Client secret
          secret: true
        - id: china_test_tenant_id
          type: string
          label: Tenant ID
          secret: true
      required:
        - china_test_client_id
        - china_test_client_secret
        - china_test_tenant_id

    injectors:
      extra_vars:
        china_test_client_id: !unsafe '{{ china_test_client_id }}'
        china_test_client_secret: !unsafe '{{ china_test_client_secret }}'
        china_test_tenant_id: !unsafe '{{ china_test_tenant_id }}'
# =====================================================
  - name: CRT_LDC_AAP_SPN_China_Prod_Credential
    description: LDC AAP SPN China Prod credential
    kind: cloud
    inputs:
      fields:
        - id: china_prod_client_id
          type: string
          label: Client ID
          secret: true
        - id: china_prod_client_secret
          type: string
          label: Client secret
          secret: true
        - id: china_prod_tenant_id
          type: string
          label: Tenant ID
          secret: true
      required:
        - china_prod_client_id
        - china_prod_client_secret
        - china_prod_tenant_id

    injectors:
      extra_vars:
        china_prod_client_id: !unsafe '{{ china_prod_client_id }}'
        china_prod_client_secret: !unsafe '{{ china_prod_client_secret }}'
        china_prod_tenant_id: !unsafe '{{ china_prod_tenant_id }}'
# =====================================================
# ================== CLOUD END ========================
# =====================================================