---
all:
  hosts:
    awx:
      ansible_host: 127.0.0.1
      ansible_connection: local
      controller_port: 8013
    test-linux:
      ansible_host: 172.22.0.5
      ansible_connection: ssh
      ansible_user: "{{ linux_user }}"
      ansible_password: "{{ linux_password }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    test-windows:
      ansible_host: 172.22.0.6
      ansible_connection: winrm
      ansible_port: 5985
      ansible_winrm_transport: ntlm
      ansible_winrm_server_cert_validation: ignore
      ansible_user: "{{ windows_user }}"
      ansible_password: "{{ windows_password }}"
  children:
    automationcontroller:
      hosts:
        awx:
    linux:
      hosts:
        test-linux:
    windows:
      hosts:
        test-windows:
