---
# Source Control credentials used by AWX Projects
controller_scm_credentials_all:
  - name: AWX_AZDO_PAT
    credential_type: Source Control
    organization: AWXPOC
    description: Azure DevOps PAT for Git HTTPS
    inputs:
      username: "{{ awx_ado_username | default('Tsvetelin.Maslarski-ext@ldc.com') }}"
      password: "{{ awx_ado_token }}"
